---
- connection: local
  gather_facts: true
  hosts: localhost

  vars:
    #Environment 
    var_azure_rm_subid: "2b7550e0-f0bc-4530-bbe2-79d186b5e6b8"
    var_location: "east us"

    var_resourceGroupName: "INFRA_DEV_RG001" 
    var_vnetName: "DEV-VNET01"
    var_subnetName: "DEV-SUBNET01"
    var_addressPrefix: "192.168.15.0/25"
    var_subnetAddressPrefix: "192.168.15.0/27"
    var_keyVaultName: "DEVTECHPROJKEYVAULT001"

    #OMS 
    var_omsSubscriptionId: "2b7550e0-f0bc-4530-bbe2-79d186b5e6b8"
    var_omsResourceGroup: "OMS_DEV_RG"
    var_omsWorkspaceName: "logsworkspacedev"

    # Tags
    var_owner: "luisapalechor.lp@gmail.com"
    var_deploymentId: "DEV01"
    var_productApp: "DevProject"
    var_global_chargeCode: "DEVP001"
    var_environment: "Development"
    
  tasks:
    - name: "AZ Login to Azure"
      shell: >
        az login --service-principal
        -u "{{ AZURE_RM_CLIENTID }}"
        -p '{{ AZURE_RM_SECRET }}'
        --tenant "{{ AZURE_RM_TENANTID }}" && az account set --subscription "{{ var_azure_rm_subid }}"
  
    - name: "Create resource group"     
      vars:
        resource_id_var: "resource_group"
        resource_group_env: "{{ var_resourceGroupName }}"
        var_retries: 5
        var_delay: 10
      include_tasks: tasks/resource-group/playbooks/Create_resource-group.yml

    - name: "Create vnet and subnet"
      vars:
        resource_id_var: "vnet_subnet"
        var_env_vnetName: "{{ var_vnetName }}"
        var_env_addressPrefix: "{{ var_addressPrefix }}}"
        var_env_subnetName: "{{ var_subnetName }}"
        var_env_subnetAddressPrefix: "{{ var_subnetAddressPrefix }}"
        var_retries: 5
        var_delay: 10
      include_tasks: tasks/vnet/playbooks/Create_vnet.yml

    - name: "Create key vault"
      vars:
        resource_id_var: "key_vault"
        regular_expression: "subscriptions/{{ var_azure_rm_subid }}/resourceGroups/{{resource_group}}/providers/Microsoft.KeyVault/vaults/(.*)\\\\"
        var_env_keyVaultName: "{{var_keyVaultName}}"
        var_tier: "Standard"
        var_subnetId: "NULL"
        var_ObjectsId: "d97d973b-b743-41d1-a1f5-d5042d795836"
        var_enableSoftDelete: false
        var_retries: 20
        var_delay: 10
        workspaceId: "/subscriptions/{{ var_omsSubscriptionId }}/resourceGroups/{{ var_omsResourceGroup }}/providers/Microsoft.OperationalInsights/workspaces/{{ var_omsWorkspaceName }}"
      include_tasks: tasks/key-vault/playbooks/Create_key-vault.yml
      
    - name: "AZ Add key vaul permissions"
      shell: >
        az keyvault set-policy 
        --name "KEYVAULTDEVLUI00123e" 
        --object-i 6e300f6c-5712-4ceb-8477-c44ac1e076b8 
        --secret-permissions get list purge recover restore set

    - name: "Create Web Server"
      vars:
        var_virtualNetworkId: "/subscriptions/{{ var_azure_rm_subid }}/resourceGroups/{{ var_resourceGroupName }}/providers/Microsoft.Network/virtualNetworks/{{ var_vnetName }}"
        var_vmName: "webserver01"
        var_computerSize: "Basic_A1"
        var_adminUserName: "luisapale"
        var_StorageAccountName: "vmlxdiagnostic01websr"
        var_StorageAccountId: "/subscriptions/{{ var_azure_rm_subid }}/resourceGroups/{{ var_resourceGroupName }}/providers/Microsoft.Storage/storageAccounts/{{ var_StorageAccountName }}"
        var_StorageAccountType: "Standard_LRS"
        var_StorageAccountKind: "Storage"
        var_rolePurpose: "Linux Virtual Machine"
      include_tasks: tasks/vm-linux/playbooks/Create_vm-linux.yml

    - name: "Create SQL Server"
      vars:
        var_virtualNetworkId: "/subscriptions/{{ var_azure_rm_subid }}/resourceGroups/{{ var_resourceGroupName }}/providers/Microsoft.Network/virtualNetworks/{{ var_vnetName }}"
        var_vmName: "sqlserver01"
        var_computerSize: "Basic_A1"
        var_adminUserName: "luisapale"
        var_StorageAccountName: "vmlxdiagnostic01sqlsv"
        var_StorageAccountId: "/subscriptions/{{ var_azure_rm_subid }}/resourceGroups/{{ var_resourceGroupName }}/providers/Microsoft.Storage/storageAccounts/{{ var_StorageAccountName }}"
        var_StorageAccountType: "Standard_LRS"
        var_StorageAccountKind: "Storage"
        var_rolePurpose: "Linux Virtual Machine"
      include_tasks: tasks/vm-linux/playbooks/Create_vm-linux.yml

    - name: "Create Load Balancer"
      vars:
        var_virtualNetworkId: "/subscriptions/{{ var_azure_rm_subid }}/resourceGroups/{{ var_resourceGroupName }}/providers/Microsoft.Network/virtualNetworks/{{ var_vnetName }}"
        var_vmName: "loadbalancer"
        var_computerSize: "Basic_A1"
        var_adminUserName: "luisapale"
        var_StorageAccountName: "vmlxdiagnostic01lb"
        var_StorageAccountId: "/subscriptions/{{ var_azure_rm_subid }}/resourceGroups/{{ var_resourceGroupName }}/providers/Microsoft.Storage/storageAccounts/{{ var_StorageAccountName }}"
        var_StorageAccountType: "Standard_LRS"
        var_StorageAccountKind: "Storage"
        var_rolePurpose: "Linux Virtual Machine"
      include_tasks: tasks/vm-linux/playbooks/Create_vm-linux.yml